### PR TITLE
Ensure that ES6 modules in Foundation JS are transpiled prior to being imported to Ember

### LINKED ISSUE #33: Including individual Foundation JS components does not transpile from ES6 to ES5
The individual Foundation JS component files are written in ES6 and need to be transpiled for browsers that don't support ES6 features. As far as I can tell, it does not appear that Ember's build process transpiles ES6 when included in the vendors.js file via `app.import(...)`.

ember-cli-babel is installed and transpiles files from `app/` just fine. If there is an option to tell the CLI to transpile the vendor files as well, I have not found it, please let me know.

`'ember-cli-foundation-6-sass': {
            'foundationJs': [
                'core',
                ...
            ]
};`

This appears to be supported, but may be functionality left over from versions that did not require transpiling.

### PR DESCRIPTION
**Pull request by localpcguy**
Since Ember's `app.import(...)` does not transpile ES6, this PR adds a transpile step to the files before they are included.

Fixes #33

### CODE REVIEW

**Comment by localpcguy** [comment]
Thanks for merging - I forgot to bump the plugin version so you can update it on npm, is that something you could do so this version can be pulled from npm? Thanks!

**Comment by acoustep** [comment]
No problem, thanks for contributing!

I've updated the version, however, I can't publish to NPM right now. I'll be able to do it when I get home in a few hours.

**Comment by localpcguy** [comment]
No problem, I appreciate the responsiveness on this!

**Comment by acoustep** [comment]
Thanks for waiting, I've just published 0.0.14!

**Pull request merged**
