### PR TITLE
Solve issue with reveals across multiple pages loads

### LINKED ISSUE #53: Reveal not working across multiple loads
I'm trying to use a reveal in an ember loaded route, it works the first time you load the route, but it will fail to add the `data-reveal` attribute on subsequent load.

Versions
Ember: 2.10
ember-cli-foundation-6-sass: 0.0.18
foundation-6: 6.3.0

### PR DESCRIPTION
**Pull request by tomtom5152**
Ensure widget elements are actually destroyed when the widget is destroyed.

Closes #53

### CODE REVIEW

**Comment by tomtom5152** [comment]
Apologies for the mess of this PR, the issue proved more complex as I investigated further.

**Comment by acoustep** [comment]
No problem and thanks!

**Comment by tomtom5152** [comment]
Magic, any ideas when the next release might be including these changes?

**Comment by acoustep** [comment]
I've pushed version 0.0.19 which should have them in.

**Pull request merged**
